apiVersion: v1
kind: Service
metadata:
  name: node-app
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3333'
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - port: 3333
      targetPort: 3333
      nodePort: 30001 # Optional: Kubernetes will allocate one if not specified
