apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1 # Initial number of replicas
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: node-app:latest # Replace with your actual image
        imagePullPolicy: Never
        ports:
        - containerPort: 3333
        resources:
          requests:
            cpu: "100m" # Requested CPU 
            memory: "100Mi" # Requested Memory
          limits:
            cpu: "150m"     # Limits for usage
            memory: "150Mi"
        env:
          - name: MYSQL_HOST
            value: "mysql"
          - name: MYSQL_USER
            value: "will"
          - name: MYSQL_PASSWORD
            value: "pass"
          - name: MYSQL_DATABASE
            value: "mydb"
