apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: node-app:latest # Replace with your actual image
        imagePullPolicy: Never
        ports:
        - containerPort: 3333
        env:
          - name: MYSQL_HOST
            value: "mysql"
          - name: MYSQL_USER
            value: "will"
          - name: MYSQL_PASSWORD
            value: "pass"
          - name: MYSQL_DATABASE
            value: "mydb"
