apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc # Name of the persistent volume claim
spec:
  accessModes:
    - ReadWriteOnce # Volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi # Request 1 GB of storage
